# Generated by Django 5.1.4 on 2025-01-13 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensor_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='motionhistory',
            name='humidity',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='motionhistory',
            name='temperature',
            field=models.FloatField(null=True),
        ),
    ]
